In [1]:
import numpy as np

In [5]:
mydata = np.arange(0,20)

In [6]:
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
np.reshape(mydata,(10,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [10]:
np.reshape(mydata,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
matrix = np.reshape(mydata,(5,4),order='c')
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [14]:
matrix[3,3]

15

In [15]:
matrix = np.reshape(mydata,(5,4),order='f')
print(matrix)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [16]:
#another way for reshape function
#np.arange has already converted the data to array
#we can directly:
mydata.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
#--------

In [19]:
#np.array function

l = ["hello ","all","floks"]
m = ["what","a","day"]
n = [1,2,3]

[l,m,n]

[['hello ', 'all', 'floks'], ['what', 'a', 'day'], [1, 2, 3]]

In [21]:
np.array((l,m,n))


array([['hello ', 'all', 'floks'],
       ['what', 'a', 'day'],
       ['1', '2', '3']], dtype='<U6')

In [22]:
print(np.array((l,m,n)))

[['hello ' 'all' 'floks']
 ['what' 'a' 'day']
 ['1' '2' '3']]
